/* ============================================================
   sw.js — offline

   The whole point of this file: the game has to work with no network at
   all, because it is meant to be installed on a phone and played
   anywhere. That means every module, both CSVs and all 158 creature
   sprites have to be in a cache before the network goes away.

   Two tiers, and the split matters:

     CORE       the shell — markup, styles, modules, the creature data.
                Without any one of these the game does not start, so
                install fails loudly if one cannot be fetched.

     PRECACHE   the sprites, read from precache.json. Perhaps 13 MB, so a
                single failure must not fail the install — an unregistered
                creature with a missing sprite is a small blemish, a
                refusing service worker is a broken app. They are cached
                individually and failures are counted, not thrown.

   Anything not in either tier is cached the first time it is fetched, so
   a sprite that slipped through still works offline the second time.

   Bump CACHE_VERSION to ship an update. Old caches are deleted on
   activate, which is also what stops a stale module pairing with a fresh
   one.
   ============================================================ */

const CACHE_VERSION = 'v7';
const CACHE_NAME = `pinball-creatures-${CACHE_VERSION}`;

/**
 * The shell. Listed by hand rather than generated, because this is exactly
 * the set of files whose absence means "no game", and that deserves to be
 * visible and reviewable.
 */
const CORE = [
  './',
  'index.html',
  'styles.css',
  'manifest.webmanifest',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-maskable-512.png',
  'Elemental Awakening Creatures.csv',
  'Elemental Awakening Creatures Stats and Moves.csv',
  'Galactic Adventures.csv',
  'Raid Exclusive - Search and Go.csv',
  'Exclusives2.csv',
  'Exclusives3.csv',
  'js/main.js',
  'js/data.js',
  'js/state.js',
  'js/persist.js',
  'js/physics.js',
  'js/table.js',
  'js/render.js',
  'js/game.js',
  'js/views.js',
  'js/audio.js',
  'js/ui.js'
];

/* ---------------------------------------------------------------
   Install
   --------------------------------------------------------------- */

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);

    // Core first, and let a failure reject: a half-installed shell is worse
    // than no service worker at all.
    await cache.addAll(CORE);

    // Then the bulk. One at a time so a single 404 cannot take the rest with
    // it, and with `reload` so an install never adopts a stale HTTP-cached copy.
    let cached = 0, failed = 0;
    for (const url of await precacheList()) {
      try {
        const res = await fetch(new Request(url, { cache: 'reload' }));
        if (!res.ok) throw new Error(String(res.status));
        await cache.put(url, res);
        cached++;
      } catch {
        failed++;
      }
    }
    console.log(`[sw] precached ${cached} assets, ${failed} failed`);

    // Take over straight away rather than waiting for every tab to close.
    await self.skipWaiting();
  })());
});

/**
 * The sprite list, generated by tools/build-precache.ps1.
 *
 * Optional on purpose. Without it the game still installs and still works
 * offline for everything in CORE; sprites then arrive through the runtime
 * cache as they are first seen.
 */
async function precacheList() {
  try {
    const res = await fetch(new Request('precache.json', { cache: 'reload' }));
    if (!res.ok) return [];
    const data = await res.json();
    return Array.isArray(data.assets) ? data.assets : [];
  } catch {
    return [];
  }
}

/* ---------------------------------------------------------------
   Activate
   --------------------------------------------------------------- */

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('pinball-creatures-') && key !== CACHE_NAME) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

/* ---------------------------------------------------------------
   Fetch
   --------------------------------------------------------------- */

self.addEventListener('fetch', event => {
  const req = event.request;

  // Only GETs, and only our own origin. The test harness POSTs its results,
  // and intercepting that would be actively unhelpful.
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Never cache the self test or its endpoint.
  if (url.pathname.endsWith('/selftest.html') || url.pathname.startsWith('/__')) return;

  event.respondWith(cacheFirst(req));
});

/**
 * Cache first, network as a fallback, and store whatever the network gives.
 *
 * Cache first rather than network first because this is a game: a table that
 * stutters while a module is re-fetched over a bad connection is worse than a
 * version that is a few minutes stale, and CACHE_VERSION handles updates.
 */
async function cacheFirst(req) {
  const cache = await caches.open(CACHE_NAME);

  const hit = await cache.match(req, { ignoreSearch: true });
  if (hit) return hit;

  try {
    const res = await fetch(req);
    // Opaque and error responses are not worth keeping.
    if (res.ok && res.type === 'basic') cache.put(req, res.clone()).catch(() => {});
    return res;
  } catch {
    // Offline and not cached. For a navigation, the shell is a far better
    // answer than a browser error page.
    if (req.mode === 'navigate') {
      const shell = await cache.match('index.html');
      if (shell) return shell;
    }
    return new Response('Offline and not cached.', {
      status: 503,
      headers: { 'Content-Type': 'text/plain' }
    });
  }
}
